#!/usr/bin/env node
// scripts/make-page.mjs — the fixpoint. index.html carries the SAME sentinel.mjs + kestrelledger.mjs the tests and the
// mutation gate prove, inlined verbatim, and re-runs the deterministic measureLedger() in the browser. Every number on the
// page and in llms.txt is GENERATED by the kernel (one-kernel-rule). CI regenerates and fails on any diff. CRLF is stripped
// so the inlined kernel is byte-identical to the module. The live demo exhales signed 6-byte packets into a REAL IndexedDB
// and, on reload, inhales them back — the node resumes in the exact state it closed in.
import { readFileSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

const at = (f) => new URL('../' + f, import.meta.url);
const read = (f) => readFileSync(at(f), 'utf8').replace(/\r\n/g, '\n');
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const URL_LIVE = 'https://sjgant80-hub.github.io/kestrel-ledger/';
const REPO = 'https://github.com/sjgant80-hub/kestrel-ledger';

const prereg = JSON.parse(read('data/prereg.json'));
let run = null;
try { run = JSON.parse(read('data/run.json')); } catch { run = null; }
const SEALED = !run;

// verify the page's live kernel equals the committed record (fixpoint) when measured.
const L = await import(pathToFileURL(at('kestrelledger.mjs').pathname).href).catch(() => import('../kestrelledger.mjs'));
const liveM = L.measureLedger(run ? run.seed : 2026, run ? run.N : 10000);
if (run && (liveM.byteIdentical !== run.reconstruction.byteIdentical || liveM.ratioPayloadVsJson !== run.storage.ratioPayloadVsJson)) {
  console.error('DRIFT: run.json != kernel measureLedger'); process.exit(1);
}

// ── inline the real kernel: sentinel (IIFE) + kestrelledger (IIFE) ──────────────────────────────────────────────────────
const stripModule = (src) => src
  .replace(/^export\s+default\s+\{[\s\S]*?\};\s*$/gm, '')
  .replace(/^export\s*\{[\s\S]*?\};\s*$/gm, '')
  .replace(/^export\s+/gm, '');
const SENTINEL_API = 'pack,unpack,foldWitness,check,phantom,fingerprint,replayStore,rng,WIRE,PAYLOAD,SIG,OPCODES,RESOURCES';
const LEDGER_API = 'DB_NAME,DB_VERSION,STORES,GENOME_KEY,OPNAME,resourceNames,baseState,genome,cloneState,levelFor,applyPrimorialFold,canonicalState,reconstruct,verifyReplay,rehydrateReplay,syntheticCommands,packAll,mutationJson,withSig,measureLedger,pack,unpack,foldWitness,check,fingerprint,replayStore,WIRE,PAYLOAD,SIG,OPCODES,RESOURCES';
const sentinelBody = stripModule(read('sentinel.mjs'));
const ledgerBody = stripModule(read('kestrelledger.mjs').replace(/^import\s[\s\S]*?from\s+'\.\/sentinel\.mjs';\s*$/gm, ''));
const KERNEL =
  `const __S=(function(){\n${sentinelBody}\nreturn {${SENTINEL_API}};})();\n` +
  `const __L=(function(){const {${SENTINEL_API}}=__S;\n${ledgerBody}\nreturn {${LEDGER_API}};})();\n` +
  `const K=Object.assign({},__S,__L);\n`;

// ── the sealed / measured numbers for the static page ───────────────────────────────────────────────────────────────────
const num = (v) => (v == null ? '—' : v);
const coordRatio = run ? run.storage.ratioPayloadVsJson : null;
const signedRatio = run ? run.storage.ratioSignedVsJsonSigned : null;
const replayMs = run ? run.replay.replayMs10k : null;
const payloadKB = run ? run.storage.ledgerPayloadKB : null;
const jsonMB = run ? run.storage.jsonMB : null;

const claimPills = SEALED
  ? '<span class="pill ok">byte-identical — sealed</span><span class="pill ok">storage — sealed</span><span class="pill ok">replay — sealed</span><span class="pill warn">tamper-rejected — sealed</span>'
  : `<span class="pill ok">byte-identical reconstruction ✓</span><span class="pill ok">coordinate ${coordRatio}×</span><span class="pill ok">10k replay ${replayMs}ms</span><span class="pill warn">poisoned ledger rejected ✓</span>`;

const resultsTable = SEALED
  ? prereg.predictions.map((p) => `<tr><td class="mono">${esc(p.id)}</td><td class="dim">${esc(p.claim)}</td><td class="n dim">sealed</td></tr>`).join('\n')
  : [
    ['P1 · reconstruction', `N=${run.N} mutations → drop RAM → inhale → <b>byte-identical</b> to the pre-close surface`, run.verdict['P1-reconstruction'] ? 'PASS' : 'FAIL'],
    ['P2 · storage (coordinate)', `6-byte ledger ${payloadKB} KB vs traditional JSON ${jsonMB} MB = <b>${coordRatio}×</b>`, run.verdict['P2-storage-coordinate'] ? 'PASS' : 'FAIL'],
    ['P3 · storage (signed, honest)', `fully signed 71-byte rows vs signed JSON = <b>${signedRatio}×</b> (the 64-byte Ed25519 floor dominates)`, run.verdict['P3-storage-signed-honest'] ? 'PASS' : 'FAIL'],
    ['P4 · replay speed', `replay ${run.replay.packets.toLocaleString ? run.N.toLocaleString() : run.N} packets in <b>${replayMs} ms</b>`, run.verdict['P4-replay-speed'] ? 'PASS' : 'FAIL'],
    ['P5 · tamper-rejected', `forged + tampered + over-budget + replay all dropped on inhale; poisoned ledger == clean = <b>${run.tamper.poisonedEqualsClean}</b>`, run.verdict['P5-tamper-rejected'] ? 'PASS' : 'FAIL'],
    ['P6 · bounded-replay home', `fresh store misses a reboot replay; rehydrated-from-ledger store <b>catches</b> it (closes SENTINEL v2 #1)`, run.verdict['P6-bounded-home'] ? 'PASS' : 'FAIL'],
  ].map(([id, v, s]) => `<tr><td class="mono">${esc(id)}</td><td>${v}</td><td class="n"><span class="pill ${s === 'PASS' ? 'ok' : 'bad'}">${s}</span></td></tr>`).join('\n');

const inputRows = Object.entries(prereg.inputs || {}).map(([f, h]) => `<tr><td class="mono">${esc(f)}</td><td class="mono dim" style="word-break:break-all">${esc(h)}</td></tr>`).join('\n');

const SCHEMA = {
  '@context': 'https://schema.org', '@type': 'SoftwareSourceCode', name: 'KESTREL-LEDGER',
  description: 'IndexedDB as the Shadow Fold: a binary append-only ledger of signed 6-byte Primorial-Fold packets. The node resumes in the exact state it closed in — byte-identical reconstruction, a poisoned ledger rejected by the Ed25519 verify-before-parse gate.',
  codeRepository: REPO, url: URL_LIVE, programmingLanguage: 'JavaScript', license: 'https://opensource.org/licenses/MIT', author: { '@type': 'Person', name: 'Kar' },
  isBasedOn: { '@type': 'SoftwareSourceCode', name: 'SENTINEL', url: 'https://sjgant80-hub.github.io/sentinel/' },
};
const FAQ = {
  '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: [
    { '@type': 'Question', name: 'What is the Shadow Fold ledger?', acceptedAnswer: { '@type': 'Answer', text: 'IndexedDB treated not as a JSON database but as a binary append-only ledger: every state transition is a signed 6-byte Primorial-Fold packet appended to a store. When the tab closes, RAM is flushed but the packets have already exhaled to local disk, so nothing is lost.' } },
    { '@type': 'Question', name: 'How does a node resume after the tab closes?', acceptedAnswer: { '@type': 'Answer', text: SEALED ? 'On boot KESTREL opens the DB, reads the immutable DNA, reads the whole binary ledger, and fast-forwards: it replays each 6-byte packet onto the base state and reconstructs the exact state the node was in the moment the window closed. Sealed; measured on the next commit and re-derived on CI.' : `On boot it opens the DB, reads the DNA, and replays the ${run.N.toLocaleString ? run.N.toLocaleString() : run.N} packets onto the base state in ${replayMs} ms, reconstructing a state byte-identical to the one it closed in. No cloud server is pinged.` } },
    { '@type': 'Question', name: 'Can a corrupted ledger corrupt the node?', acceptedAnswer: { '@type': 'Answer', text: 'No. Every packet is re-verified against its Ed25519 signature before its six bytes are parsed on the way in. A forged, tampered, over-budget or replayed packet in the ledger is dropped, so the reconstructed state is identical to a clean ledger\'s.' } },
  ],
};

const page = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>KESTREL-LEDGER — IndexedDB as the Shadow Fold</title>
<meta name="description" content="IndexedDB as a binary append-only ledger of signed 6-byte packets. Close the tab, reopen it, and the node resumes in the exact state it closed in — reconstruction byte-identical, a poisoned ledger rejected by the Ed25519 gate.">
<link rel="canonical" href="${URL_LIVE}">
<meta property="og:title" content="KESTREL-LEDGER — IndexedDB as the Shadow Fold">
<meta property="og:description" content="Close the tab, reopen it, resume mid-thought. The intelligence exhales into the local metal as 6-byte signed packets.">
<meta property="og:type" content="website">
<meta property="og:url" content="${URL_LIVE}">
<link rel="manifest" href="manifest.webmanifest">
<meta name="theme-color" content="#0b0e14">
<script type="application/ld+json">${JSON.stringify(SCHEMA)}</script>
<script type="application/ld+json">${JSON.stringify(FAQ)}</script>
<style>
:root{--bg:#0b0e14;--panel:#121725;--panel2:#0f1420;--ink:#e6edf6;--dim:#8b97ab;--line:#232c40;--hot:#5eead4;--acc:#7c9cff;--warn:#f5b54a;--bad:#ff6b6b;--ok:#4ade80;--mono:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}
@media(prefers-color-scheme:light){:root:not([data-theme=dark]){--bg:#f5f7fb;--panel:#fff;--panel2:#eef2f8;--ink:#121725;--dim:#5a6678;--line:#dde3ee;--hot:#0d9488;--acc:#3454d1}}
:root[data-theme=dark]{--bg:#0b0e14;--panel:#121725;--panel2:#0f1420;--ink:#e6edf6;--dim:#8b97ab;--line:#232c40;--hot:#5eead4;--acc:#7c9cff}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.6 system-ui,-apple-system,Segoe UI,Roboto,sans-serif;-webkit-text-size-adjust:100%}
.wrap{max-width:900px;margin:0 auto;padding:0 16px 80px}
header{padding:48px 0 24px;border-bottom:1px solid var(--line)}
h1{font-size:clamp(28px,6vw,46px);margin:0 0 8px;letter-spacing:-.02em}
h2{font-size:clamp(20px,4vw,26px);margin:40px 0 12px;letter-spacing:-.01em}
h3{font-size:17px;margin:22px 0 8px}
.tag{display:inline-block;font:600 12px var(--mono);color:var(--hot);border:1px solid var(--line);border-radius:999px;padding:3px 10px;margin-bottom:14px}
.lede{color:var(--dim);font-size:18px;max-width:64ch}
.card{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:18px;margin:16px 0}
.card.flat{background:var(--panel2)}
table{width:100%;border-collapse:collapse;font-size:14px;margin:8px 0}
th,td{text-align:left;padding:8px 10px;border-bottom:1px solid var(--line);vertical-align:top}
th{color:var(--dim);font-weight:600;font-size:12px;text-transform:uppercase;letter-spacing:.04em}
td.n{text-align:right;white-space:nowrap}
.hot{color:var(--hot)}.dim{color:var(--dim)}
code,.mono{font-family:var(--mono);font-size:13px}
.byte{display:inline-flex;gap:4px;flex-wrap:wrap;font-family:var(--mono)}
.byte span{background:var(--panel2);border:1px solid var(--line);border-radius:6px;padding:4px 8px;font-size:13px;min-width:34px;text-align:center}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}
.grid3{display:grid;grid-template-columns:1fr 1fr 1fr;gap:12px}
@media(max-width:640px){.grid,.grid3{grid-template-columns:1fr}}
button{font:600 14px system-ui;color:#06121a;background:var(--hot);border:0;border-radius:9px;padding:10px 16px;cursor:pointer}
button.ghost{background:transparent;color:var(--ink);border:1px solid var(--line)}
button.bad{background:var(--bad);color:#fff}
button:disabled{opacity:.5;cursor:not-allowed}
.log{font:12px/1.5 var(--mono);background:var(--panel2);border:1px solid var(--line);border-radius:9px;padding:10px;max-height:220px;overflow:auto;white-space:pre-wrap;word-break:break-all}
.pill{display:inline-block;font:600 11px var(--mono);padding:2px 8px;border-radius:999px;border:1px solid var(--line);margin:2px}
.pill.ok{color:var(--ok);border-color:var(--ok)}.pill.bad{color:var(--bad);border-color:var(--bad)}.pill.warn{color:var(--warn);border-color:var(--warn)}
.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin:10px 0}
a{color:var(--acc)}
.foot{color:var(--dim);font-size:13px;margin-top:40px;border-top:1px solid var(--line);padding-top:20px}
.stat{background:var(--panel2);border:1px solid var(--line);border-radius:12px;padding:14px}
.stat .big{font:700 26px var(--mono);color:var(--hot);letter-spacing:-.02em}
.stat .lbl{color:var(--dim);font-size:12px;text-transform:uppercase;letter-spacing:.04em}
.resume{border:1px solid var(--hot);border-radius:12px;padding:14px;background:color-mix(in srgb,var(--hot) 8%,transparent)}
</style>
</head>
<body>
<div class="wrap">
<header>
<span class="tag">SHADOW FOLD · fall-os persistence · step ④ of 4</span>
<h1>IndexedDB is the Shadow Fold</h1>
<p class="lede">Close the tab and the lit surface dissolves — RAM is flushed, the web app dies. KESTREL does not. The intelligence has already <b>exhaled</b> into the local metal as signed 6-byte packets. Reopen, and it <b>inhales</b> the whole binary ledger back and resumes in the exact state it closed in. No cloud server is pinged.</p>
<div class="row">${claimPills}</div>
</header>

<div class="card resume" id="resume-card">
<h3 style="margin-top:0">↻ On boot — germination from the Shadow Fold</h3>
<div id="resume-body" class="dim">opening KESTREL_OS…</div>
</div>

<h2>Do something, then close this tab</h2>
<p class="lede" style="font-size:16px">Each button folds one 6-byte packet into <code>state_mutations</code> in a <b>real</b> IndexedDB, signed with an Ed25519 key kept in <code>crypto_wallet</code>. Then just <b>reload the page</b> (or close and reopen it): the node resumes exactly here. Nothing was written to a server.</p>
<div class="card">
<div class="grid3">
<div><div class="stat"><div class="big" id="s-level">0</div><div class="lbl">level</div></div></div>
<div><div class="stat"><div class="big" id="s-seq">0</div><div class="lbl">mutations (seq)</div></div></div>
<div><div class="stat"><div class="big" id="s-xp">0</div><div class="lbl">xp</div></div></div>
</div>
<div class="row" style="margin-top:14px">
<button id="do-write" disabled>write (+1 xp)</button>
<button id="do-grant" disabled>grant (+2 xp)</button>
<button id="do-couple" disabled>couple (+3 xp)</button>
<button id="do-heal" disabled>heal</button>
<button id="do-forge" class="ghost" disabled>fire a FORGED packet</button>
<button id="do-reset" class="bad ghost">reset node</button>
</div>
<div class="row"><span class="pill" id="ledger-stat">ledger: 0 packets</span><span class="pill" id="wallet-stat">wallet: —</span></div>
<div class="log" id="demo-log" aria-live="polite"></div>
<p class="dim" style="font-size:13px;margin:8px 0 0">The forged packet is appended to the ledger with a random signature. It is <b>dropped on the next inhale</b> (reload) by the verify-before-parse gate — proof that a poisoned Shadow Fold cannot corrupt the node.</p>
</div>

<h2>The six bytes &amp; the three sovereign stores</h2>
<div class="card">
<div class="byte" style="margin-bottom:10px">
<span title="opcode">op</span><span title="source·target">s·t</span><span title="resources">res</span><span title="budget lo">b₀</span><span title="budget hi">b₁</span><span title="κ-witness fold">κ</span>
</div>
<p style="margin:0 0 12px;color:var(--dim);font-size:14px">A whole state transition in six bytes: opcode · two 4-bit node indices · an 8-bit capability bitmask · a uint16 budget · the primorial-fold κ-witness. On disk it travels signed: <code>[sourceId:1][packet:6][signature:64] = 71 bytes</code>. The codec and the verify-before-parse gate are <a href="https://sjgant80-hub.github.io/sentinel/">SENTINEL</a>'s live, mutation-gated kernel, reused here.</p>
<div class="grid3">
<div class="card flat"><b>genome_core</b><p class="dim" style="font-size:13px;margin:6px 0 0">the immutable DNA (<code>v1</code>) — the Konomi/LIGHT recipe + structural laws. Written once, only read.</p></div>
<div class="card flat"><b>crypto_wallet</b><p class="dim" style="font-size:13px;margin:6px 0 0">the local Ed25519 keypair + the capability budget — the physical gate.</p></div>
<div class="card flat"><b>state_mutations</b><p class="dim" style="font-size:13px;margin:6px 0 0">the nervous system — every 6-byte opcode appended as a raw binary row. Append-only.</p></div>
</div>
</div>

<h2>${SEALED ? 'Sealed: the predictions, pinned before the measurement' : 'Measured: the sealed claims, re-derived on CI'}</h2>
<p class="lede" style="font-size:16px">${SEALED ? 'Committed as its own commit before any measurement. The results land on the next commit and are re-derived on CI from exactly the inputs hashed below — so the seal provably predates the result. Re-run the kernel yourself now, below.' : 'Every number is generated by the inlined kernel and re-derived byte-for-byte on GitHub\'s runner from the sealed inputs.'}</p>
<div class="card">
<table>
<thead><tr>${SEALED ? '<th>prediction</th><th>claim</th><th>state</th>' : '<th>claim</th><th>result</th><th>verdict</th>'}</tr></thead>
<tbody>${resultsTable}</tbody>
</table>
${SEALED
  ? `<p style="margin:10px 0 6px;color:var(--dim);font-size:13px"><b>The inputs, pinned (sha256) — the measurement must re-derive from exactly these:</b></p><table><thead><tr><th>input</th><th>sha256</th></tr></thead><tbody>${inputRows}</tbody></table>`
  : `<p style="margin:6px 0 0;color:var(--dim);font-size:13px"><b>Read it honestly:</b> the big ratio is the <b>coordinate</b> ledger (${coordRatio}× — ${payloadKB} KB where traditional JSON is ${jsonMB} MB). Stored fully signed per the spec, the 64-byte Ed25519 signature is irreducible, so the durable ledger is only <b>${signedRatio}×</b> over signed JSON — the honest floor. The headline is not the signature; it is that the node reconstructs byte-identically and a poisoned ledger is rejected.</p>`}
</div>

<div class="row"><button id="rerun">Re-run the sealed measurement in your browser</button><span id="rerun-out" class="pill">idle</span></div>
<div class="log" id="rerun-log" aria-live="polite"></div>

<h2>Why this is not a traditional database</h2>
<div class="card flat">
<p style="margin:0 0 10px">A traditional web app flushes RAM on close and persists aggregate JSON state it hopes it wrote in time. KESTREL stores <b>raw physics</b>: the 6-byte packets and their 64-byte signatures, as ArrayBuffers. The entire state history is kilobytes, not megabytes, and is unreadable to standard browser scraping — a local cryptographic cipher. A browser crash, a power death or an abrupt close after a packet is committed loses nothing: the mathematical coordinate is already in the shadow fold. On boot the femtoLLM reads the immutable DNA, then replays the microscopic ledger — 6-byte packets, so 10,000 past actions fast-forward in milliseconds — and the intelligence resumes mid-thought.</p>
<p style="margin:0" class="dim">This also gives SENTINEL's bounded replay window a durable home (its v2 flag #1): the window is RAM-only and empty after a reboot, so a recent replay would slip through — but rehydrated from the ledger on inhale, the window is restored and the replay is caught.</p>
</div>

<p class="foot">
Every number on this page is generated by the mutation-gated kernel <code>kestrelledger.mjs</code> (built on <code>sentinel.mjs</code>), inlined below and re-run in your browser. · <a href="${REPO}">source</a> · <a href="https://sjgant80-hub.github.io/sentinel/">SENTINEL</a> · <a href="https://sjgant80-hub.github.io/fall-airgap/">FALL-AIRGAP</a> · MIT for the code.<br>
The 6-byte Primorial-Fold codec and the κ-witness are the Konomi architecture / LIGHT, created by <b>Thomas Frumkin</b> (used with permission); the verify-before-parse gate and the bounded replay store carry from SENTINEL. Built by Kar.
</p>
</div>

<script id="kernel" type="text/plain">
${KERNEL}
</script>
<script>
// run the SAME kernel this page is built from, in the browser (new Function so const declarations scope cleanly).
const K=new Function(document.getElementById('kernel').textContent+'\\nreturn K;')();
const $=(id)=>document.getElementById(id);
const log=(el,s)=>{el.textContent+=(el.textContent?'\\n':'')+s;el.scrollTop=el.scrollHeight;};

// ── re-run the sealed measurement (pure kernel, deterministic) ───────────────────────────────
$('rerun').onclick=()=>{
  const out=$('rerun-out'), box=$('rerun-log'); box.textContent='';
  const t0=performance.now();
  const m=K.measureLedger(${run ? run.seed : 2026}, ${run ? run.N : 10000});
  const ms=Math.round((performance.now()-t0)*1000)/1000;
  log(box,'N = '+m.N+' mutations');
  log(box,'byte-identical reconstruction: '+m.byteIdentical);
  log(box,'coordinate ledger '+m.ledgerPayloadBytes+'B vs JSON '+m.jsonBytes+'B = '+m.ratioPayloadVsJson+'×');
  log(box,'signed ledger '+m.ledgerSignedBytes+'B vs signed JSON '+m.jsonSignedBytes+'B = '+m.ratioSignedVsJsonSigned+'×');
  log(box,'reconstruct + measure here: '+ms+'ms · fold '+m.fold);
  out.textContent=m.byteIdentical?'byte-identical ✓':'MISMATCH'; out.className='pill '+(m.byteIdentical?'ok':'bad');
};

// ── the live Shadow-Fold node: REAL IndexedDB + WebCrypto Ed25519 ─────────────────────────────
const DB_NAME=K.DB_NAME, S=K.STORES, PAYLOAD=K.PAYLOAD, WIRE=K.WIRE, SIG=K.SIG, OPS=K.OPCODES;
const edOK=(()=>{try{return !!(crypto&&crypto.subtle);}catch{ return false; }})();
const req=(r)=>new Promise((res,rej)=>{r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});
const txDone=(t)=>new Promise((res,rej)=>{t.oncomplete=()=>res();t.onerror=()=>rej(t.error);t.onabort=()=>rej(t.error);});
let DB=null, wallet=null, SOURCE=3, surface=null;

function openDB(){return new Promise((res,rej)=>{const o=indexedDB.open(DB_NAME,K.DB_VERSION);
  o.onupgradeneeded=()=>{const db=o.result;
    if(!db.objectStoreNames.contains(S.GENOME))db.createObjectStore(S.GENOME);
    if(!db.objectStoreNames.contains(S.WALLET))db.createObjectStore(S.WALLET);
    if(!db.objectStoreNames.contains(S.MUTATIONS))db.createObjectStore(S.MUTATIONS,{autoIncrement:true});};
  o.onsuccess=()=>res(o.result); o.onerror=()=>rej(o.error);});}
async function putGenome(g){const t=DB.transaction(S.GENOME,'readwrite');t.objectStore(S.GENOME).put(g,K.GENOME_KEY);await txDone(t);}
async function getGenome(){const t=DB.transaction(S.GENOME,'readonly');return (await req(t.objectStore(S.GENOME).get(K.GENOME_KEY)))||null;}
async function putWallet(w){const t=DB.transaction(S.WALLET,'readwrite');t.objectStore(S.WALLET).put(w,'self');await txDone(t);}
async function getWallet(){const t=DB.transaction(S.WALLET,'readonly');return (await req(t.objectStore(S.WALLET).get('self')))||null;}
async function appendFrame(frame){const t=DB.transaction(S.MUTATIONS,'readwrite');t.objectStore(S.MUTATIONS).add(frame.slice().buffer);await txDone(t);}
async function getLedger(){const t=DB.transaction(S.MUTATIONS,'readonly');const rows=await req(t.objectStore(S.MUTATIONS).getAll());return (rows||[]).map(r=>new Uint8Array(r));}

async function ensureWallet(){
  let w=await getWallet();
  if(w&&w.privateKey){ wallet=w; SOURCE=w.source; return; }
  if(!edOK){ wallet={source:SOURCE,budget:2000,privateKey:null,publicKey:null}; await putWallet(wallet); return; }
  const kp=await crypto.subtle.generateKey({name:'Ed25519'},false,['sign','verify']); // non-extractable, persisted as CryptoKey
  wallet={source:SOURCE,budget:2000,privateKey:kp.privateKey,publicKey:kp.publicKey};
  await putWallet(wallet);
}
function signedMessage(payload){const m=new Uint8Array(1+PAYLOAD);m[0]=SOURCE&0xFF;m.set(payload,1);return m;}
function frameOf(payload,sig){const raw=new Uint8Array(WIRE);raw[0]=SOURCE&0xFF;raw.set(payload,1);raw.set(sig,1+PAYLOAD);return raw;}
async function signFrame(cmd){const p=K.pack(Object.assign({},cmd,{source:SOURCE&0xF}));
  let sig; if(wallet.privateKey){ sig=new Uint8Array(await crypto.subtle.sign({name:'Ed25519'},wallet.privateKey,signedMessage(p))); }
  else { sig=new Uint8Array(SIG); } // no WebCrypto: zero sig (will be dropped on gated inhale — honest)
  return frameOf(p,sig);}

// the gated INHALE in the browser: a faithful async re-expression of the kernel's verifyReplay (sync kernel can't await
// WebCrypto). Same codec (unpack/fingerprint/applyPrimorialFold), real Ed25519 verify, same verdicts.
async function inhale(){
  const g=(await getGenome())||K.genome();
  const frames=await getLedger();
  let state=K.cloneState(g.baseState); const seen=new Set(); let applied=0; const rejected={};
  const rej=(r)=>{rejected[r]=(rejected[r]||0)+1;};
  for(const raw of frames){
    if(!(raw instanceof Uint8Array)||raw.length!==WIRE){rej('bad-length');continue;}
    let good=false;
    if(edOK&&wallet&&wallet.publicKey){ try{ good=await crypto.subtle.verify({name:'Ed25519'},wallet.publicKey,raw.subarray(1+PAYLOAD),raw.subarray(0,1+PAYLOAD)); }catch{ good=false; } }
    else { good=true; } // no WebCrypto in this browser: trust local bytes (documented)
    if(!good){rej('forged');continue;}
    const nonce=K.fingerprint(raw); if(seen.has(nonce)){rej('replay');continue;}
    const u=K.unpack(raw.subarray(1,1+PAYLOAD)); if(!u.ok){rej(u.reason);continue;}
    seen.add(nonce); state=K.applyPrimorialFold(state,raw.subarray(1,1+PAYLOAD)); applied++;
  }
  return {state,frames:frames.length,applied,rejected};
}

function paint(){ $('s-level').textContent=surface.level; $('s-seq').textContent=surface.seq; $('s-xp').textContent=surface.xp; }
function enable(on){ ['do-write','do-grant','do-couple','do-heal','do-forge'].forEach(id=>$(id).disabled=!on); }

async function exhaleCmd(cmd,forge){
  // EXHALE: fire the signed packet into the shadow fold FIRST (before repaint) — crash-safe
  let frame=await signFrame(cmd);
  if(forge){ const s=new Uint8Array(SIG); crypto.getRandomValues?crypto.getRandomValues(s):s.fill(7); frame=frameOf(K.pack(Object.assign({},cmd,{source:SOURCE&0xF})),s); }
  await appendFrame(frame);
  if(!forge){ surface=K.applyPrimorialFold(surface,frame.subarray(1,1+PAYLOAD)); paint(); }
  const n=await (async()=>{const t=DB.transaction(S.MUTATIONS,'readonly');return await req(t.objectStore(S.MUTATIONS).count());})();
  $('ledger-stat').textContent='ledger: '+n+' packets · '+(n*WIRE)+' B on disk';
  log($('demo-log'),(forge?'↯ FORGED ':'→ exhaled ')+K.OPNAME[cmd.opcode]+'  ['+Array.from(frame.subarray(1,1+PAYLOAD)).join(',')+']'+(forge?'  (random signature — will be dropped on next reload)':''));
}

async function boot(){
  const rb=$('resume-body');
  try{
    DB=await openDB();
    let g=await getGenome(); const fresh=!g; if(!g){ g=K.genome(); await putGenome(g); }
    await ensureWallet();
    const woke=await inhale();
    surface=woke.state;
    const rejTotal=Object.values(woke.rejected).reduce((a,b)=>a+b,0);
    if(woke.frames===0){
      rb.innerHTML='<b>fresh node.</b> No shadow fold yet — do something below, then reload this page and watch it resume.';
    } else {
      rb.innerHTML='<b>resumed mid-thought.</b> Replayed <b>'+woke.frames+'</b> packets from the Shadow Fold → level <b>'+surface.level+'</b>, seq <b>'+surface.seq+'</b>, xp <b>'+surface.xp+'</b>'+(rejTotal?' · <span class="pill bad">dropped '+rejTotal+' poisoned packet(s) on the way in</span>':' · <span class="pill ok">ledger clean</span>')+'. No server was pinged.';
    }
    $('wallet-stat').textContent='wallet: '+(wallet&&wallet.privateKey?'Ed25519 key (persisted)':'no WebCrypto — local-trust mode');
    const n=(await (async()=>{const t=DB.transaction(S.MUTATIONS,'readonly');return await req(t.objectStore(S.MUTATIONS).count());})());
    $('ledger-stat').textContent='ledger: '+n+' packets · '+(n*WIRE)+' B on disk';
    paint(); enable(true);
  }catch(e){ rb.innerHTML='<span class="pill bad">IndexedDB unavailable</span> '+(e&&e.message?e.message:e); }
}
$('do-write').onclick=()=>exhaleCmd({opcode:OPS.WRITE,target:1,resources:0,budget:0},false);
$('do-grant').onclick=()=>exhaleCmd({opcode:OPS.GRANT,target:2,resources:3,budget:150},false);
$('do-couple').onclick=()=>exhaleCmd({opcode:OPS.COUPLE,target:3,resources:0,budget:0},false);
$('do-heal').onclick=()=>exhaleCmd({opcode:OPS.HEAL,target:1,resources:0,budget:0},false);
$('do-forge').onclick=()=>exhaleCmd({opcode:OPS.GRANT,target:7,resources:255,budget:1999},true);
$('do-reset').onclick=async()=>{ try{ DB&&DB.close(); await new Promise((res)=>{const d=indexedDB.deleteDatabase(DB_NAME);d.onsuccess=d.onerror=d.onblocked=()=>res();}); location.reload(); }catch(e){ log($('demo-log'),'reset failed: '+e.message); } };
$('rerun').click();
boot();
</script>
</body>
</html>`;

writeFileSync(at('index.html'), page);

// llms.txt
const llms = `# KESTREL-LEDGER
> IndexedDB as the Shadow Fold: a binary append-only ledger of signed 6-byte Primorial-Fold packets. Exhale on every state transition; inhale on boot by replaying the ledger onto the immutable DNA. The node resumes in the exact state it closed in.

Live: ${URL_LIVE}
Source: ${REPO}
Built on SENTINEL (https://sjgant80-hub.github.io/sentinel/) and FALL-AIRGAP. Codec: Thomas Frumkin's Konomi / LIGHT primorial-fold (used with permission).

${SEALED
  ? `## Sealed, awaiting measurement
Predictions + the sha256 of every input committed as their own commit before the measurement. Inputs pinned:
${Object.entries(prereg.inputs || {}).map(([f, h]) => `- ${f}: sha256 ${h}`).join('\n')}
The results land on the next commit and are re-derived on CI from exactly these inputs.`
  : `## Measured (re-derived on CI from the sealed inputs)
- Reconstruction: exhale ${run.N} mutations, drop RAM, inhale -> BYTE-IDENTICAL to the pre-close state (${run.reconstruction.byteIdentical}).
- Storage (coordinate): 6-byte ledger ${run.storage.ledgerPayloadKB} KB vs traditional JSON ${run.storage.jsonMB} MB = ${run.storage.ratioPayloadVsJson}x.
- Storage (signed, honest): fully signed 71-byte rows vs signed JSON = ${run.storage.ratioSignedVsJsonSigned}x (the 64-byte Ed25519 signature is irreducible).
- Replay: ${run.N} packets replayed in ${run.replay.replayMs10k} ms.
- Tamper: a forged, tampered, over-budget or replayed packet in the ledger is rejected on inhale; poisoned ledger == clean (${run.tamper.poisonedEqualsClean}).
- Bounded-replay home: rehydrating SENTINEL's window from the ledger catches a reboot replay a fresh store misses (closes SENTINEL v2 flag #1).`}

## The three sovereign object stores (DB: KESTREL_OS)
- genome_core: the immutable DNA (v1) — the Konomi/LIGHT recipe + structural laws.
- crypto_wallet: the local Ed25519 keypair + the capability budget (the physical gate).
- state_mutations: every 6-byte opcode appended as a raw binary row (append-only).
`;
writeFileSync(at('llms.txt'), llms);
console.log(SEALED ? 'index.html + llms.txt generated · SEALED state (no run.json yet)' : 'index.html + llms.txt generated · coordinate ' + coordRatio + '× · signed ' + signedRatio + '× · replay ' + replayMs + 'ms');
